import React from 'react';
import {afterEach,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import ReceiptReview from '../components/receipts/ReceiptReview.jsx';
import * as api from '../lib/agent-api.js';
vi.mock('../lib/agent-api.js');afterEach(()=>{cleanup();vi.clearAllMocks();});
it('lets users clear and retype item amounts without inserting zero',async()=>{
 const user=userEvent.setup();
 const review={receiptId:'r',candidate:{merchant:'店',merchant_address:'住所',date:'2026-10-07',time:'15:14',total:100,currency:'JPY',payment_method:'cash',items:[{name:'商品',amount:100}]},missingFields:[],matches:[],locationResolution:{id:'loc',receiptId:'r',revision:1,input:{merchant:'店',merchantAddress:'住所'},status:'resolved',expiresAt:Date.now()/1000+3600}};
 api.proposeReceipt.mockResolvedValue({});
 render(<ReceiptReview review={review} threadId="t" busy={false} setBusy={vi.fn()} onProposed={vi.fn()}/>);
 await user.selectOptions(screen.getByLabelText('保存先'),'new');
 const item=screen.getByLabelText('品目金額 1');
 await user.clear(item);
 expect(item.value).toBe('');
 expect(screen.getByRole('button',{name:'変更案を確認'}).disabled).toBe(true);
 await user.type(item,'125');
 expect(item.value).toBe('125');
 const total=screen.getByLabelText('金額 1');
 await user.clear(total);
 expect(total.value).toBe('');
 await user.type(total,'125');
 await user.click(screen.getByLabelText('時刻を確認しました'));
 await user.click(screen.getByRole('button',{name:'変更案を確認'}));
 expect(api.proposeReceipt.mock.lastCall[1].draft).toMatchObject({amount:125,items:[{name:'商品',amount:125}]});
});
it('blocks empty total amounts even when no items are saved',async()=>{
 const user=userEvent.setup();
 const review={receiptId:'r',candidate:{merchant:'店',merchant_address:'住所',total:100,currency:'JPY',items:[]},missingFields:[],matches:[],locationResolution:{id:'loc',receiptId:'r',revision:1,input:{merchant:'店',merchantAddress:'住所'},status:'resolved',expiresAt:Date.now()/1000+3600}};
 render(<ReceiptReview review={review} threadId="t" busy={false} setBusy={vi.fn()} onProposed={vi.fn()}/>);
 await user.selectOptions(screen.getByLabelText('保存先'),'new');
 await user.clear(screen.getByLabelText('金額 1'));
 expect(screen.getByRole('button',{name:'変更案を確認'}).disabled).toBe(true);
 fireEvent.submit(screen.getByRole('button',{name:'変更案を確認'}).closest('form'));
 expect(api.proposeReceipt).not.toHaveBeenCalled();
});
it('requires confirming the inherited address before preparing a proposal',async()=>{
 const input={merchant:'店',branch:null,locality:null,merchantAddress:'住所A'};
 const review={receiptId:'r',candidate:{merchant:'店',merchant_address:' ',total:100,currency:'JPY'},missingFields:[],matches:[{reason:'near',transaction:{id:'A',title:'店',merchantAddress:'住所A'}}],locationResolution:{id:'loc',receiptId:'r',revision:1,input:{...input,merchantAddress:null},status:'needs_input'}};
 api.confirmReceiptAddress.mockResolvedValue({id:'loc',receiptId:'r',revision:2,input,status:'resolved',sourceTransactionId:'A',expiresAt:Date.now()/1000+3600});api.proposeReceipt.mockResolvedValue({});
 render(<ReceiptReview review={review} threadId="t" busy={false} setBusy={vi.fn()} onProposed={vi.fn()}/>);
 fireEvent.change(screen.getByLabelText('保存先'),{target:{value:'A'}});
 expect(screen.getByRole('button',{name:'変更案を確認'}).disabled).toBe(true);
 fireEvent.click(screen.getByRole('button',{name:'この住所を確認した'}));
 await waitFor(()=>expect(screen.getByRole('button',{name:'変更案を確認'}).disabled).toBe(false));
 fireEvent.submit(screen.getByRole('button',{name:'変更案を確認'}).closest('form'));
 expect(api.proposeReceipt.mock.lastCall[1].draft.merchantAddress).toBe('住所A');
 expect(api.proposeReceipt.mock.lastCall[1].location.resolutionId).toBe('loc');
 fireEvent.change(screen.getByLabelText('原本・本人確認済みの住所'),{target:{value:''}});
 expect(screen.getByRole('button',{name:'変更案を確認'}).disabled).toBe(true);
});
it('requires explicit duplicate selection and preserves missing fields and discrepancy',async()=>{
 const review={receiptId:'r',mimeType:'image/png',candidate:{merchant:'店',date:null,time:null,total:90,currency:'JPY',payment_method:null,items:[{name:'品目',amount:100}]},missingFields:['date','time','payment_method'],itemMismatch:true,matches:[{reason:'near',transaction:{id:'t',title:'食材',date:'2026-10-03T12:00',amount:90}}]};
 render(<ReceiptReview review={review} threadId="thread" busy={false} setBusy={vi.fn()} onProposed={vi.fn()}/>);
 expect(screen.getByRole('img',{name:'レシートのプレビュー'}).getAttribute('src')).toContain('/receipts/r');
 expect(screen.getByText(/品目合計と合計金額が一致しません/)).toBeTruthy();
 expect(screen.getByRole('button',{name:'変更案を確認'}).disabled).toBe(true);
 fireEvent.change(screen.getByRole('combobox',{name:'保存先'}),{target:{value:'t'}});
 expect(api.proposeReceipt).not.toHaveBeenCalled();
 expect(screen.getByLabelText('日時 1').value).toBe('');
});
it('uses calculated net amounts and keeps original evidence visible after manual edits',()=>{
 const review={receiptId:'r',candidate:{merchant:'店',date:'2026-10-01',time:'08:45',total:1161,paid_total:1139,currency:'JPY',items:[{name:'商品',amount:130}]},missingFields:[],matches:[],preparedDraft:{amount:1139,items:[{name:'商品',amount:1139}]},calculation:{issues:[],grossTotal:1161,discountTotal:22,paidTotal:1139,rows:[{name:'商品',printed:130,basis:'exclusive',rate:8,addedTax:10,gross:140,discount:3,net:137}]}};
 render(<ReceiptReview review={review} threadId="thread" busy={false} setBusy={vi.fn()} onProposed={vi.fn()}/>);
 expect(screen.getByLabelText('金額 1').value).toBe('1139');
 expect(screen.getByLabelText('品目金額 1').value).toBe('1139');
 expect(screen.getByRole('region',{name:'税込金額の計算根拠'})).toBeTruthy();
 fireEvent.change(screen.getByLabelText('金額 1'),{target:{value:'1200'}});
 expect(screen.getByText(/自動計算後に変更されています/)).toBeTruthy();
});
it('requires explicit manual verification when tax evidence is inconsistent',()=>{
 const review={receiptId:'r',locationResolution:{id:'loc',receiptId:'r',revision:1,input:{merchant:'店',merchantAddress:'住所'},status:'resolved',expiresAt:Date.now()/1000+3600},candidate:{merchant:'店',merchant_address:'住所',total:100,currency:'JPY',items:[{name:'商品',amount:100}]},missingFields:[],matches:[],calculation:{rows:[],issues:['税区分を確認してください。']},preparedDraft:null};
 render(<ReceiptReview review={review} threadId="thread" busy={false} setBusy={vi.fn()} onProposed={vi.fn()}/>);
 fireEvent.change(screen.getByRole('combobox',{name:'保存先'}),{target:{value:'new'}});
 expect(screen.getByRole('button',{name:'変更案を確認'}).disabled).toBe(true);
 fireEvent.click(screen.getByLabelText('原本と照合し、金額・品目を確認しました'));
 expect(screen.getByRole('button',{name:'変更案を確認'}).disabled).toBe(false);
});
it('keeps address edits separate for each receipt target',()=>{
 const review={receiptId:'r',candidate:{merchant:'店',total:100,currency:'JPY'},missingFields:[],matches:['A','B'].map(id=>({reason:'near',transaction:{id,title:id,merchantAddress:'住所'+id}}))};
 render(<ReceiptReview review={review} threadId="t" busy={false} setBusy={vi.fn()} onProposed={vi.fn()}/>);
 const select=screen.getByLabelText('保存先');
 fireEvent.change(select,{target:{value:'A'}});expect(screen.getByLabelText('原本・本人確認済みの住所').value).toBe('住所A');
 fireEvent.change(screen.getByLabelText('原本・本人確認済みの住所'),{target:{value:'修正A'}});
 fireEvent.change(select,{target:{value:'B'}});expect(screen.getByLabelText('原本・本人確認済みの住所').value).toBe('住所B');
 fireEvent.change(select,{target:{value:'new'}});expect(screen.getByLabelText('原本・本人確認済みの住所').value).toBe('');
 fireEvent.change(select,{target:{value:'A'}});expect(screen.getByLabelText('原本・本人確認済みの住所').value).toBe('修正A');
});
it('blocks_proposal_until_location_resolved_and_preserves_amount_items_while_searching',async()=>{
 let finish;api.searchReceiptLocation.mockReturnValue(new Promise(resolve=>{finish=resolve;}));
 const input={merchant:'店',branch:null,locality:null,merchantAddress:null};const resolution={id:'current-resolution',receiptId:'r',revision:1,input,status:'needs_input',expiresAt:Date.now()/1000+3600};
 const review={receiptId:'r',candidate:{merchant:'店',total:1139,currency:'JPY',items:[{name:'商品',amount:1139}]},missingFields:[],matches:[],locationResolution:resolution};
 render(<ReceiptReview review={review} threadId="t" busy={false} setBusy={vi.fn()} onProposed={vi.fn()}/>);
 fireEvent.change(screen.getByLabelText('保存先'),{target:{value:'new'}});fireEvent.click(screen.getByRole('button',{name:'店舗を再検索'}));
 expect(screen.getByLabelText('金額 1').value).toBe('1139');expect(screen.getByLabelText('品目金額 1').value).toBe('1139');expect(screen.getByRole('button',{name:'変更案を確認'}).disabled).toBe(true);
 finish({...resolution,revision:2,status:'resolved',method:'google_unique'});await waitFor(()=>expect(screen.getByRole('button',{name:'変更案を確認'}).disabled).toBe(false));
 fireEvent.change(screen.getByLabelText('金額 1'),{target:{value:'1200'}});fireEvent.change(screen.getByLabelText('品目金額 1'),{target:{value:'1200'}});expect(screen.getByRole('button',{name:'変更案を確認'}).disabled).toBe(false);
 fireEvent.change(screen.getByLabelText('支店名'),{target:{value:'別支店'}});expect(screen.getByRole('button',{name:'変更案を確認'}).disabled).toBe(true);
});
it('reconfirms_same_pending_proposal_and_preserves_source_address',async()=>{
 const input={merchant:'店',branch:'支店',locality:'地域',merchantAddress:'検索根拠の住所'};
 const resolution={id:'loc',receiptId:'r',revision:2,input,status:'resolved',method:'google_unique',expiresAt:Date.now()/1000+3600};
 const review={receiptId:'r',candidate:{merchant:'読取店',total:100,currency:'JPY'},missingFields:[],matches:[],locationResolution:resolution};
 const proposal={id:'same',revision:3,metadata:{targetChoice:'new',receiptLocation:{input,method:'google_unique'}},commands:[{kind:'transaction.create',data:{merchant:'店',merchantAddress:null,title:'修正内容',amount:200,items:[],type:'expense',category:'その他'}}]};
 api.getReceiptLocation.mockResolvedValue(resolution);api.reconfirmReceiptProposal.mockResolvedValue({...proposal,revision:4});
 render(<ReceiptReview review={review} proposal={proposal} threadId="t" busy={false} setBusy={vi.fn()} onProposed={vi.fn()}/>);
 await waitFor(()=>expect(screen.getByRole('button',{name:'変更案を確認'}).disabled).toBe(false));
 expect(screen.getByLabelText('金額 1').value).toBe('200');expect(screen.getByLabelText('原本・本人確認済みの住所').value).toBe(input.merchantAddress);
 fireEvent.submit(screen.getByRole('button',{name:'変更案を確認'}).closest('form'));
 expect(api.reconfirmReceiptProposal.mock.lastCall[0]).toBe('same');expect(api.reconfirmReceiptProposal.mock.lastCall[1].draft.merchantAddress).toBe(input.merchantAddress);expect(api.proposeReceipt).not.toHaveBeenCalled();
});
it('preserves amount and item edits when inherited search resolves later',async()=>{
 let finish;api.searchReceiptLocation.mockReturnValue(new Promise(resolve=>{finish=resolve;}));
 const input={merchant:'店',branch:null,locality:null,merchantAddress:'原本住所'};
 const resolution={id:'loc',receiptId:'r',revision:1,input,status:'needs_input',expiresAt:Date.now()/1000+3600};
 const review={receiptId:'r',candidate:{merchant:'店',merchant_address:'原本住所',total:100,currency:'JPY',items:[{name:'原本品目',amount:100}]},missingFields:[],matches:[{reason:'near',transaction:{id:'A',title:'店',merchantPlace:{provider:'google',placeId:'saved'}}}],locationResolution:resolution};
 api.proposeReceipt.mockResolvedValue({});
 render(<ReceiptReview review={review} threadId="t" busy={false} setBusy={vi.fn()} onProposed={vi.fn()}/>);
 fireEvent.change(screen.getByLabelText('保存先'),{target:{value:'A'}});
 fireEvent.click(screen.getByRole('button',{name:'保存先の店舗参照を確認'}));
 fireEvent.change(screen.getByLabelText('金額 1'),{target:{value:'250'}});
 fireEvent.change(screen.getByLabelText('品目名 1'),{target:{value:'修正品目'}});
 fireEvent.change(screen.getByLabelText('品目金額 1'),{target:{value:'250'}});
 finish({...resolution,revision:2,input:{...input,merchantAddress:null},status:'resolved',method:'existing_google',sourceTransactionId:'A'});
 await waitFor(()=>expect(screen.getByRole('button',{name:'変更案を確認'}).disabled).toBe(false));
 expect(screen.getByLabelText('原本・本人確認済みの住所').value).toBe('');
 expect(screen.getByLabelText('金額 1').value).toBe('250');
 expect(screen.getByLabelText('品目名 1').value).toBe('修正品目');
 expect(screen.getByLabelText('品目金額 1').value).toBe('250');
 fireEvent.submit(screen.getByRole('button',{name:'変更案を確認'}).closest('form'));
 expect(api.proposeReceipt.mock.lastCall[1].draft).toMatchObject({amount:250,items:[{name:'修正品目',amount:250}],merchantAddress:null});
});
it('loads current confirmation for pending proposal instead of stale receipt snapshot',async()=>{
 const input={merchant:'店',branch:null,locality:null,merchantAddress:'住所'};
 const stale={id:'loc',receiptId:'r',revision:1,input,status:'resolved',expiresAt:Date.now()/1000+3600};
 const current={...stale,revision:5};api.getReceiptLocation.mockResolvedValue(current);
 const review={receiptId:'r',candidate:{merchant:'店',total:100,currency:'JPY'},missingFields:[],matches:[],locationResolution:stale};
 const proposal={id:'same',revision:2,metadata:{targetChoice:'new',receiptLocation:{input,method:'user_address'}},commands:[{kind:'transaction.create',data:{merchant:'店',merchantAddress:'住所',title:'店',amount:100,items:[],type:'expense',category:'その他'}}]};
 render(<ReceiptReview review={review} proposal={proposal} threadId="t" busy={false} setBusy={vi.fn()} onProposed={vi.fn()}/>);
 await waitFor(()=>expect(api.getReceiptLocation).toHaveBeenCalledWith('t','r',expect.any(AbortSignal)));
 await waitFor(()=>expect(screen.getByRole('button',{name:'変更案を確認'}).disabled).toBe(false));
 fireEvent.submit(screen.getByRole('button',{name:'変更案を確認'}).closest('form'));
 expect(api.reconfirmReceiptProposal.mock.lastCall[1].location.revision).toBe(5);
});
it('keeps edits made while loading current pending confirmation and rejects late initial GET',async()=>{
 let first,second;api.getReceiptLocation.mockReturnValueOnce(new Promise(resolve=>{first=resolve;})).mockReturnValueOnce(new Promise(resolve=>{second=resolve;}));
 const input={merchant:'店',branch:null,locality:null,merchantAddress:'住所'},current={id:'loc',receiptId:'r',revision:5,input,status:'resolved',expiresAt:Date.now()/1000+3600};
 const review={receiptId:'r',candidate:{merchant:'店',total:100,currency:'JPY'},missingFields:[],matches:[],locationResolution:{...current,revision:1}};
 const proposal={id:'same',revision:2,metadata:{targetChoice:'new',receiptLocation:{input,method:'user_address'}},commands:[{kind:'transaction.create',data:{merchant:'店',merchantAddress:'住所',title:'店',amount:100,items:[],type:'expense',category:'その他'}}]};
 render(<ReceiptReview review={review} proposal={proposal} threadId="t" busy={false} setBusy={vi.fn()} onProposed={vi.fn()}/>);
 fireEvent.change(screen.getByLabelText('店舗名'),{target:{value:'編集店舗'}});fireEvent.change(screen.getByLabelText('金額 1'),{target:{value:'250'}});
 await waitFor(()=>expect(api.getReceiptLocation).toHaveBeenCalledTimes(2));expect(api.getReceiptLocation.mock.calls[0][2].aborted).toBe(true);
 second(current);await waitFor(()=>expect(screen.getByRole('button',{name:'店舗を再検索'}).disabled).toBe(false));first({...current,revision:1});
 expect(screen.getByLabelText('店舗名').value).toBe('編集店舗');expect(screen.getByLabelText('金額 1').value).toBe('250');expect(screen.getByRole('button',{name:'変更案を確認'}).disabled).toBe(true);
 api.confirmReceiptAddress.mockResolvedValue({...current,revision:6,input:{...input,merchant:'編集店舗'}});fireEvent.click(screen.getByRole('button',{name:'この住所を確認した'}));await waitFor(()=>expect(screen.getByRole('button',{name:'変更案を確認'}).disabled).toBe(false));expect(api.confirmReceiptAddress.mock.lastCall[2].revision).toBe(5);
});
it('reopens confirmed source fields and preserves financial and local edits on refresh',()=>{
 const input={merchant:'訂正した店舗',branch:'本人支店',locality:'本人地域',merchantAddress:'本人確認した住所'};
 const resolution={id:'loc',receiptId:'r',revision:4,input,status:'resolved',method:'user_address',sourceTransactionId:null,expiresAt:Date.now()/1000+3600};
 const review={receiptId:'r',candidate:{merchant:'OCR店舗',merchant_address:'OCR住所',total:100,currency:'JPY',items:[{name:'商品',amount:100}]},preparedDraft:{amount:120,items:[{name:'計算済品目',amount:120}]},missingFields:[],matches:[],locationResolution:resolution};
 const props={review,threadId:'t',busy:false,setBusy:vi.fn(),onProposed:vi.fn()};
 const view=render(<ReceiptReview {...props}/>);
 expect(screen.getByLabelText('店舗名').value).toBe(input.merchant);
 expect(screen.getByLabelText('原本・本人確認済みの住所').value).toBe(input.merchantAddress);
 expect(screen.getByLabelText('支店名').value).toBe(input.branch);
 expect(screen.getByLabelText('地域').value).toBe(input.locality);
 expect(screen.getByLabelText('金額 1').value).toBe('120');
 fireEvent.change(screen.getByLabelText('保存先'),{target:{value:'new'}});
 expect(screen.getByRole('button',{name:'変更案を確認'}).disabled).toBe(false);
 fireEvent.change(screen.getByLabelText('店舗名'),{target:{value:'編集中の店舗'}});
 fireEvent.change(screen.getByLabelText('原本・本人確認済みの住所'),{target:{value:'編集中の住所'}});
 fireEvent.change(screen.getByLabelText('金額 1'),{target:{value:'250'}});
 fireEvent.change(screen.getByLabelText('品目金額 1'),{target:{value:'250'}});
 view.rerender(<ReceiptReview {...props} review={{...review,locationResolution:{...resolution}}}/>);
 expect(screen.getByLabelText('店舗名').value).toBe('編集中の店舗');
 expect(screen.getByLabelText('原本・本人確認済みの住所').value).toBe('編集中の住所');
 expect(screen.getByLabelText('金額 1').value).toBe('250');
 expect(screen.getByLabelText('品目金額 1').value).toBe('250');
 expect(screen.getByRole('button',{name:'変更案を確認'}).disabled).toBe(true);
});
