// @vitest-environment node
import { it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { createOfflineStyle } from '../../demo/maps/style.js';
import { validateMapAssets } from '../../../tools/demo/prepare-map.mjs';
import manifest from '../../demo/maps/manifest.json';
it('bundles a valid bounded archive and every licensed resource',async()=>{await expect(validateMapAssets()).resolves.toBeTruthy();expect(manifest.bytes).toBeLessThanOrEqual(50*1024*1024);const b=readFileSync(new URL('../../demo/public/maps/tokyo.pmtiles',import.meta.url));expect(b.subarray(0,8).toString('hex')).toBe('504d54696c657303');expect(createHash('sha256').update(b).digest('hex')).toBe(manifest.sha256);});
it('fails for missing archive/font/license or changed bytes',async()=>{for(const path of ['tokyo.pmtiles','fonts/NotoSansJP.ttf','licenses/OFL.txt'])await expect(validateMapAssets({read:async p=>{if(p.endsWith(path))throw Error('missing');return readFileSync(p);}})).rejects.toThrow();await expect(validateMapAssets({read:async p=>p.endsWith('tokyo.pmtiles')?Buffer.from('bad'):readFileSync(p)})).rejects.toThrow();});
it('produces Japanese same-site style resources under the Pages base',()=>{const style=createOfflineStyle('http://localhost:3000/Kakei/');expect(style.sources.basemap.url).toBe('pmtiles://http://localhost:3000/Kakei/maps/tokyo.pmtiles');expect(style.glyphs).toBeUndefined();expect(style.sprite).toBeUndefined();expect(style.layers.some(l=>l.type==='symbol'&&JSON.stringify(l.layout['text-field']).includes('name:ja'))).toBe(true);expect(style.layers.some(l=>l['source-layer']==='roads')).toBe(true);expect(style.layers.some(l=>l['source-layer']==='water')).toBe(true);});
it('removes only building and POI layers while preserving opaque road geometry',async()=>{const {filterTileLayers}=await import('../../../tools/demo/prepare-map.mjs');const layer=(name,extra)=>{const n=Buffer.from(name);const body=Buffer.concat([Buffer.from([10,n.length]),n,Buffer.from(extra)]);return Buffer.concat([Buffer.from([26,body.length]),body]);};const roads=layer('roads',[18,3,255,254,253]);const water=layer('water',[18,1,123]);expect(filterTileLayers(Buffer.concat([roads,layer('buildings',[18,0]),water,layer('pois',[18,0])]))).toEqual(Buffer.concat([roads,water]));});
it('loads an actual bundled vector tile through the official PMTiles reader',async()=>{const {PMTiles}=await import('pmtiles');const file=readFileSync(new URL('../../demo/public/maps/tokyo.pmtiles',import.meta.url));const archive=new PMTiles({getKey:()=> 'fixture',getBytes:async(o,n)=>({data:Uint8Array.from(file.subarray(o,o+n)).buffer})});expect(await archive.getHeader()).toMatchObject({minZoom:0,maxZoom:14,minLon:138.9,maxLon:139.95});const tile=await archive.getZxy(14,14549,6449);expect(tile?.data.byteLength).toBeGreaterThan(0);});
it('rejects referenced outside points but records unused ones without mutating snapshot',async()=>{const {checkSnapshotContainment}=await import('../../../tools/demo/prepare-map.mjs');const s={timeline:{places:{tokyo:{coordinates:[139.7,35.6]},fukuoka:{coordinates:[130.4,33.6]}},days:{day:{events:[{placeId:'tokyo'}],legs:[]}}}};const before=JSON.stringify(s);expect(checkSnapshotContainment(s,[138.9,35.45,139.95,35.95])).toMatchObject({referencedPlaces:1,unusedOutsidePlaces:['fukuoka']});expect(JSON.stringify(s)).toBe(before);s.timeline.days.day.legs=[{viaPlaceIds:['fukuoka']}];expect(()=>checkSnapshotContainment(s,[138.9,35.45,139.95,35.95])).toThrow();});
it('is accepted by the official MapLibre style validator',async()=>{const {validateStyleMin}=await import('@maplibre/maplibre-gl-style-spec');expect(validateStyleMin(createOfflineStyle('http://localhost:3000/Kakei/'))).toEqual([]);});
