const {test,expect}=require('@playwright/test');
const shots='../.superpowers/agent-ui-refresh';

test('chat entry, sidebar drafts, mobile history and approval layout remain usable',async({page})=>{
 test.skip(test.info().config.projects[0].use.baseURL!=='http://127.0.0.1:8767','isolated fake runner only');
 await page.clock.install({time:new Date('2026-10-03T10:59:30+09:00')});
 await page.goto('/#agent');
 await expect(page.getByRole('heading',{name:'おはよう',exact:true})).toBeVisible();
 await expect(page.getByText('今日は何を記録しますか？')).toHaveCount(0);
 await expect(page.getByText('家計のアシスタント')).toHaveCount(0);
 const composer=page.getByRole('form',{name:'メッセージを作成'});
 const field=page.getByRole('textbox',{name:'メッセージ'});
 await expect(composer.getByRole('button',{name:'レシートを添付'})).toBeVisible();
 expect(await composer.getByRole('button',{name:'送信',exact:true}).textContent()).toBe('');
 await page.screenshot({path:`${shots}/empty-desktop.png`,animations:'disabled'});
 await page.clock.runFor(60000);
 await expect(page.getByRole('heading',{name:'こんにちは',exact:true})).toBeVisible();
 await field.fill('食材の記録');await field.press('Control+Enter');
 await expect(page.getByRole('article',{name:'変更案'})).toBeVisible();
 const history=page.locator('#app-sidebar').getByRole('region',{name:'会話一覧'});
 await expect(history.getByRole('button',{name:'食材の記録',exact:true})).toBeVisible();
 await expect(page.getByRole('heading',{name:'こんにちは',exact:true})).toHaveCount(0);
 await field.fill('会話ごとの下書き');
 await history.getByRole('button',{name:'新しい会話'}).click();
 await expect(field).toHaveValue('');
 await field.fill('新規会話の下書き');
 await history.getByRole('button',{name:'食材の記録',exact:true}).click();
 await expect(field).toHaveValue('会話ごとの下書き');
 await page.screenshot({path:`${shots}/conversation-desktop.png`,animations:'disabled'});
 await page.setViewportSize({width:375,height:812});
 await expect(page.getByRole('button',{name:'会話履歴を開く'})).toBeVisible();
 await page.getByRole('button',{name:'会話履歴を開く'}).click();
 const dialog=page.getByRole('dialog',{name:'会話履歴'});
 await expect(dialog).toBeVisible();
 await page.screenshot({path:`${shots}/history-phone.png`,animations:'disabled'});
 await dialog.getByRole('button',{name:'新しい会話'}).click();
 await expect(dialog).not.toBeVisible();await expect(field).toHaveValue('新規会話の下書き');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:`${shots}/empty-phone.png`,animations:'disabled'});
 await page.getByRole('button',{name:'会話履歴を開く'}).click();
 await dialog.getByRole('button',{name:'食材の記録',exact:true}).click();
 await expect(field).toHaveValue('会話ごとの下書き');
 const nav=await page.locator('#app-sidebar').boundingBox();const input=await composer.boundingBox();
 expect(input.y+input.height).toBeLessThanOrEqual(nav.y);
 await page.screenshot({path:`${shots}/conversation-phone.png`,animations:'disabled'});
 await page.evaluate(()=>{Object.defineProperty(window.visualViewport,'height',{configurable:true,get:()=>470});window.visualViewport.dispatchEvent(new Event('resize'));});
 expect((await composer.boundingBox()).y+(await composer.boundingBox()).height).toBeLessThanOrEqual(470);
 await page.evaluate(()=>{delete window.visualViewport.height;window.visualViewport.dispatchEvent(new Event('resize'));});
 await page.setViewportSize({width:812,height:375});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await expect(composer.getByRole('button',{name:'送信',exact:true})).toBeInViewport();
 expect((await page.locator('.agent-history-content').boundingBox()).height).toBeGreaterThan(80);
 await page.screenshot({path:`${shots}/conversation-landscape.png`,animations:'disabled'});
});
