const {test,expect}=require('@playwright/test');
const fs=require('node:fs');const shot='../docs/verification/2026-10-08-receipt-merchant-location';
const image=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAAE0lEQVR4nGP8//8/AwwwwVl4OQCWbgMF7ZjH1AAAAABJRU5ErkJggg==','base64');
async function start(page,text){await page.goto('/#agent');await page.getByLabel('レシートファイル').setInputFiles({name:'receipt.png',mimeType:'image/png',buffer:image});await page.getByRole('textbox',{name:'メッセージ',exact:true}).fill(text);await page.getByRole('button',{name:'送信',exact:true}).click();await expect(page.getByRole('combobox',{name:'保存先'})).toBeVisible();await page.getByRole('combobox',{name:'保存先'}).selectOption('new');}
async function state(page){return(await(await page.request.get('/api/test/location-state')).json());}
async function capture(page,name){fs.mkdirSync(shot,{recursive:true});await page.screenshot({path:shot+'/'+name+'.png'});}
async function save(page){const response=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/receipt-proposals'));await page.getByRole('button',{name:'変更案を確認',exact:true}).click();const p=(await(await response).json()).proposal;await page.getByRole('button',{name:'確認して保存',exact:true}).click();await expect(page.getByText('保存済み',{exact:true})).toBeVisible();return p;}
test('ambiguous_receipt_requires_region_before_save',async({page})=>{const before=await state(page);await start(page,'曖昧');await expect(page.getByRole('button',{name:'変更案を確認',exact:true})).toBeDisabled();expect((await state(page)).transactions).toBe(before.transactions);await page.getByLabel('地域',{exact:true}).fill('サンプル市');await page.getByRole('button',{name:'店舗を再検索',exact:true}).click();await expect(page.getByRole('button',{name:'この店舗を選択'})).toHaveCount(2);await expect(page.getByLabel('地域',{exact:true})).toHaveValue('サンプル市');await page.locator('.receipt-location').scrollIntoViewIfNeeded();await capture(page,'desktop-candidates');await page.getByRole('button',{name:'この店舗を選択'}).first().click();await save(page);const after=await state(page);expect(after.transactions).toBe(before.transactions+1);expect(after.references).toBe(before.references+1);expect(after.latest.merchantAddress).toBeNull();});
test('unique_receipt_saves_reference_and_displays_address',async({page})=>{await start(page,'一意');await page.getByLabel('地域',{exact:true}).fill('サンプル市');await page.getByRole('button',{name:'店舗を再検索',exact:true}).click();await expect(page.getByText('店舗・住所を確認しました。',{exact:true})).toBeVisible();await save(page);const current=await state(page);expect(current.latest.merchantAddress).toBeNull();expect(current.latest.merchantPlace.placeId).toBe('fixture-unique');await page.goto('/#transaction/'+current.latest.id);await expect(page.getByText('架空県サンプル市1-2-3',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Google Maps',exact:true})).toBeVisible();await capture(page,'desktop-saved');});
test('changed_merchant_requires_reconfirmation',async({page})=>{
 await start(page,'一意');await page.getByLabel('地域',{exact:true}).fill('サンプル市');await page.getByRole('button',{name:'店舗を再検索',exact:true}).click();
 const response=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/receipt-proposals'));
 await page.getByRole('button',{name:'変更案を確認',exact:true}).click();const original=(await(await response).json()).proposal;
 await page.getByRole('button',{name:'店舗・住所を再確認',exact:true}).click();await page.getByLabel('店舗名',{exact:true}).fill('別の架空ストア');
 await expect(page.getByRole('button',{name:'変更案を確認',exact:true})).toBeDisabled();
 await page.getByLabel('原本・本人確認済みの住所',{exact:true}).fill('本人確認済み住所');await page.getByRole('button',{name:'この住所を確認した',exact:true}).click();
 const renewed=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/receipt-location'));await page.getByRole('button',{name:'変更案を確認',exact:true}).click();const next=(await(await renewed).json()).proposal;expect(next.id).toBe(original.id);expect(next.revision).toBeGreaterThan(original.revision);
 await page.getByRole('button',{name:'確認して保存',exact:true}).click();await expect(page.getByText('保存済み',{exact:true})).toBeVisible();expect((await state(page)).latest.merchantAddress).toBe('本人確認済み住所');
});
test('details_retry_and_duplicate_approval',async({page})=>{await start(page,'再試行');await expect(page.getByText('地点情報を取得できませんでした。',{exact:true})).toBeVisible();await page.locator('.receipt-location').scrollIntoViewIfNeeded();await capture(page,'desktop-retry');await page.getByRole('button',{name:'再読み込み',exact:true}).click();await expect(page.getByText('架空県サンプル市1-2-3',{exact:true})).toBeVisible();await page.getByRole('button',{name:'この店舗を選択',exact:true}).click();const p=await save(page),before=await state(page);const response=await page.request.post('/api/agent/proposals/'+p.id+'/approve',{headers:{Origin:'http://127.0.0.1:8768'},data:{revision:p.revision}});expect(response.ok()).toBe(true);expect((await state(page)).transactions).toBe(before.transactions);});
test('phone_keyboard_and_no_horizontal_overflow',async({page})=>{await page.setViewportSize({width:375,height:812});await start(page,'曖昧');const input=page.getByLabel('地域',{exact:true});await input.focus();await page.keyboard.type('サンプル市');await page.keyboard.press('Tab');await expect(page.getByLabel('原本・本人確認済みの住所',{exact:true})).toBeFocused();await page.locator('.receipt-location').scrollIntoViewIfNeeded();await capture(page,'phone-unresolved');await page.getByRole('button',{name:'店舗を再検索',exact:true}).click();await expect(page.getByRole('button',{name:'この店舗を選択'})).toHaveCount(2);await expect(input).toHaveValue('サンプル市');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'この店舗を選択'}).first().focus();await page.keyboard.press('Enter');await save(page);const current=await state(page);await page.goto('/#transaction/'+current.latest.id);await expect(page.getByText('架空県サンプル市1-2-3',{exact:true})).toBeVisible();await capture(page,'phone-saved');await page.getByText('架空県サンプル市1-2-3',{exact:true}).scrollIntoViewIfNeeded();await capture(page,'phone-saved-address');});
