const {test,expect}=require('@playwright/test');
const fs=require('node:fs');
test('receipt tax calculation survives review, save and reload at desktop and phone widths',async({page})=>{
 await page.goto('/');await expect(page.locator('#dashboard-view')).toHaveClass(/data-ready/);
 await page.getByRole('link',{name:'Agent Chat'}).click();
 await page.getByLabel('レシートファイル').setInputFiles({name:'receipt.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAIAAAAmkwkpAAAAE0lEQVR4nGP8//8/AwwwwVl4OQCWbgMF7ZjH1AAAAABJRU5ErkJggg==','base64')});
 await page.getByRole('textbox',{name:'メッセージ',exact:true}).fill('税込で記録');
 await page.getByRole('button',{name:'送信',exact:true}).click();
 await expect(page.getByLabel('金額 1',{exact:true})).toHaveValue('1139');
 for(const [i,amount] of [137,148,324,481,49].entries())await expect(page.getByLabel(`品目金額 ${i+1}`,{exact:true})).toHaveValue(String(amount));
 const calc=page.getByRole('region',{name:'税込金額の計算根拠'});
 await expect(calc).toContainText('1,161円');await expect(calc).toContainText('1,139円');
 await page.getByRole('combobox',{name:'保存先'}).selectOption('new');
 const dir='../.superpowers/receipt-tax';fs.mkdirSync(dir,{recursive:true});
 await calc.locator('h3').evaluate(el=>el.scrollIntoView({block:'start'}));
 await page.screenshot({path:`${dir}/desktop.png`});
 await page.setViewportSize({width:390,height:844});
 await calc.locator('h3').evaluate(el=>el.scrollIntoView({block:'start'}));
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:`${dir}/phone.png`});
 await page.getByRole('button',{name:'変更案を確認'}).click();
 await expect(page.getByRole('article',{name:'変更案'})).toBeVisible();
 await expect(calc).toContainText('1,139円');
 await page.getByRole('button',{name:'確認して保存'}).click();
 await expect(page.getByText('保存済み',{exact:true})).toBeVisible();
 await page.reload();
 await page.getByRole('link',{name:'Agent Chat'}).click();
 await page.getByRole('button',{name:'会話履歴を開く'}).click();
 await page.getByRole('button',{name:'税込で記録',exact:true}).click();
 await expect(page.getByText('保存済み',{exact:true})).toBeVisible();
 await expect(page.getByRole('region',{name:'税込金額の計算根拠'})).toContainText('1,139円');
 const response=await page.request.get('/api/transactions');
 const body=await response.json();
 const records=Array.isArray(body)?body:body.transactions;
 const saved=records.find(t=>t.merchant==='セブンイレブン 千代田店');
 expect(saved.merchantAddress).toBe('東京都千代田区二番町8-8');expect(saved.amount).toBe(1139);expect(saved.items.map(i=>i.amount)).toEqual([137,148,324,481,49]);
});
