import React,{useState} from 'react';
import PlaceSources,{unresolvedReason} from './PlaceSources.jsx';
import * as api from './lib/agent-api.js';
export default function AgentPlaces({proposal,group,act,onChange,busy}){
 const [confirmed,setConfirmed]=useState(false);
 const [selected,setSelected]=useState(group.selectedCandidateId||''),[name,setName]=useState(proposal.metadata?.authorizedPlaces?.[group.placeId]?.name||group.query),[longitude,setLongitude]=useState(''),[latitude,setLatitude]=useState('');
 const choice=group.candidates.find(c=>c.id===selected);
 const needsConfirmation=choice?.geocoding?.verification==='needs_confirmation';
 return <section className="agent-place-choice" aria-label={`${group.query} の地点候補`}><h3>地点を選択 · {group.query}</h3>{group.error&&<p className="agent-notice">{group.error}</p>}{group.truncated&&<p className="agent-notice">{group.omittedCandidates||group.omittedSources?`候補${group.omittedCandidates||0}件・出典${group.omittedSources||0}件を省略しました。`:'一部の候補・出典を省略しました。'} 検索条件を絞って再検索できます。</p>}
 {group.candidates.length?<fieldset><legend>住所と出典を確認してください</legend>{group.candidates.map(c=><div key={c.id} className="agent-place-option"><label><input type="radio" name={`place-${group.placeId}`} checked={selected===c.id} onChange={()=>{setSelected(c.id);setConfirmed(false);}} disabled={busy}/><span><strong>{c.name}</strong><span>{c.address||'住所なし'}</span></span></label><PlaceSources {...c}/>{c.geocoding?.verification==='needs_confirmation'&&<div className="agent-coordinate-review"><p>要確認 · 住所表記は一致していますが、Mapboxの照合情報が不十分です。</p><p>地図側の住所: {c.geocoding.matchedAddress}</p><a href={`https://www.openstreetmap.org/?mlat=${c.coordinates[1]}&mlon=${c.coordinates[0]}#map=18/${c.coordinates[1]}/${c.coordinates[0]}`} target="_blank" rel="noopener noreferrer">地図で位置を確認<span className="sr-only">（新しいタブで開く）</span></a>{selected===c.id&&<label className="agent-checkbox"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} disabled={busy}/>住所と地図を確認しました</label>}</div>}</div>)}<button type="button" className="secondary-button" disabled={!selected||busy||(needsConfirmation&&!confirmed)} onClick={()=>act(async()=>onChange(await api.selectPlaceCandidate(...(needsConfirmation?[proposal.id,proposal.revision,selected,true]:[proposal.id,proposal.revision,selected]))))}>この地点を選ぶ</button></fieldset>:<p>候補がありません。地域を含めて会話で再検索するか、確認した座標を入力してください。</p>}
 {(group.unlocatedCandidates||[]).length>0&&<section className="agent-unlocated" aria-label="位置未確認の店舗"><h4>位置未確認</h4><p>店舗情報は見つかりましたが、軌跡に使う座標は未確認です。</p>{group.unlocatedCandidates.map(c=><article key={c.id}><strong>{c.name}</strong><p>{c.address}</p><p>{[...new Set((c.unresolved||[]).map(unresolvedReason))].join(' ')}</p><PlaceSources sources={c.sources}/></article>)}<p>住所を補足して再検索するか、確認した座標を下から指定してください。</p></section>}
 <details><summary>座標を自分で指定する</summary><div className="agent-fields"><label>地点名<input value={name} onChange={e=>setName(e.target.value)} /></label><label>経度<input type="number" min="-180" max="180" step="any" value={longitude} onChange={e=>setLongitude(e.target.value)}/></label><label>緯度<input type="number" min="-90" max="90" step="any" value={latitude} onChange={e=>setLatitude(e.target.value)}/></label></div><button type="button" className="secondary-button" disabled={busy||!name.trim()||longitude===''||latitude===''} onClick={()=>act(async()=>onChange(await api.specifyPlace(proposal.id,proposal.revision,group.placeId,{name,coordinates:[Number(longitude),Number(latitude)]})))}>この座標を使う</button></details>
 </section>;
}
